### ISSUE TITLE
Codecov exception

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/dashboard#72]
### Describe the Bug

```
Exception in thread codecov:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 766, in run_closure
    _threading_Thread_run(self)
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/dashboard/dashboard/src/updater.py", line 63, in update_codecov
    raise requests.exceptions.HTTPError(f'Error: {response.text}')
requests.exceptions.HTTPError: Error: upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

**Comment by emerson-elgin** [comment]
from tenacity import retry, stop_after_attempt, wait_exponential
import requests

**Comment by ReenigneArcher** [comment]
@emerson-elgin thanks, I will have a look at `tenacity`. I've tried several retry mechanisms before without much success on this random error, so not really expecting anything different to be honest.
